title: yaMedicAid
description: Medicine & first aid wiki by the community.
baseurl: "/FirstAid"
url: "https://yaBobJonez.github.io"

remote_theme: pmarsceill/just-the-docs
footer_content: "Copyright &copy; 2020, yaBobJonez. Distributed under <a href=\"https://github.com/yaBobJonez/FirstAid/blob/master/LICENSE\">MPL-2.0</a>."
